# Site settings
title: Eshaan
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "EshaanTrehan.github.io" 

# User settings
username: Eshaan Trehan
user_description: Undergraduate Student at Trinity College Dublin in my penultimate year and will be completing Bachelor of Engineering in Computer Engineering in May'2024 .
user_title: Undergraduate Student
email: eshaan.trehan@gmail.com
twitter_username: lorem_ipsum
github_username:  EshaanTrehan
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
