# Site settings
title: Eshaan
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "EshaanTrehan.github.io" 

# User settings
username: Eshaan Trehan
user_description: I am a recent graduate with a strong foundation in software engineering, quantitative analysis, and machine learning. My academic background and internship experiences in the financial sector have sharpened my skills in Python, Java, Spring Boot, and cloud technologies. I am passionate about developing data-driven solutions and optimizing technical processes. I am open to new opportunities and challenges, particularly in roles that allow me to leverage my expertise in software development, quantitative analysis, and data/ risk analysis. Based in Dublin, I am also open to relocation.
user_title: Recent Graduate
email: eshaan.trehan@gmail.com
twitter_username: lorem_ipsum
github_username:  EshaanTrehan
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
