# Site settings
title: Eshaan
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "EshaanTrehan.github.io" 

# User settings
username: Eshaan Trehan
user_description: I'm currently in my final year at Trinity College Dublin (TCD), poised to earn my Bachelor of Engineering in Computer Engineering come May 2024. In 2023, I had the rewarding experience of serving as a Software Engineer Intern at Bloomberg. My academic trajectory is unique, I embarked on my undergraduate studies at Thapar Institute of Engineering & Technology (TIET) in August 2020. Through the distinctive International Engineering Programme jointly offered by TIET and TCD, I accomplished my first two years at TIET, then transitioned to TCD for the subsequent two years of the degree.
user_title: Undergraduate Student
email: eshaan.trehan@gmail.com
twitter_username: lorem_ipsum
github_username:  EshaanTrehan
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
